# Generated by Django 2.1.7 on 2019-03-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Company',
            new_name='company',
        ),
    ]
