# Generated by Django 2.1.7 on 2019-03-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_auto_20190309_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='url',
            field=models.TextField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='stock',
            name='isin',
            field=models.TextField(default='', max_length=30),
        ),
    ]
