# Generated by Django 2.1.7 on 2019-03-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_auto_20190309_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issuance_date',
            field=models.TextField(default='', max_length=20),
        ),
    ]
